name: POC Execution

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  run-poc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: bash scripts/poc.sh
